# Generated by Django 5.0.2 on 2024-02-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('EmailAddress', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Address', models.TextField()),
                ('Department', models.TextField()),
                ('YearOfStudy', models.IntegerField()),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=8)),
            ],
        ),
    ]
